### ISSUE TITLE
2) Task Runners

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#10]
# Story
Once all of the group members have the setup files on their local machines, each member will need to install Task Runners in the terminal.

# Acceptance Criteria
**When** Each member has cloned the repo
**Then** Each member will need to initialize npm 
**And** Install grunt

# Technical Notes
- Navigate to the lib/ directory in the Terminal
- ```npm init```
- ```npm install grunt matchdep grunt-contrib-watch grunt-browserify gruntify-eslint --save-dev```
- Open integrated terminal in VS Code and cd into lib/
- Run ```grunt```

**Comment by zoeames** [comment]
This should be done as part of the setup ticket.  Once the npm packages are saved into the package.json each team member just needs to run ```npm install``` and npm will install everything that shows up in the package json

**Comment by zoeames** [comment]
I have referenced this ticket in your setup ticket and am closing this one
