### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by jessrod11** [nss-evening-cohort-7/chatty-papaphobia#15]
<img width="423" alt="screen shot 2018-04-21 at 12 26 38 pm" src="https://user-images.githubusercontent.com/23087466/39219636-6fe1ef32-47f1-11e8-9f22-8ba509ef323a.png">
<img width="494" alt="screen shot 2018-04-21 at 12 26 08 pm" src="https://user-images.githubusercontent.com/23087466/39219642-75659fbc-47f1-11e8-8562-ec073bae57a2.png">

 # Story
 "As a user, one should be able to naviagte through the page via an input field,  Clear All /Send buttons, and radio buttons."

# Acceptance Criteria
**When** - the page loads, the user should see in the nav bar a logo and user icons.
**Then**- there should be a main-container that wraps around the message-container.
**And**- there should be a message container that will hold all messages
**And** - a theme container that holds the radio buttons for the themes.
**And** - a footer that sticks to the bottom and holds the clear all button, input field, and send button 

# Technical Notes

 -  ``<div id="user-nav">``  for the nav container
 - ``<div id = "main-container">`` that wraps around the message container
 -  ``<div id= "message-container">`` that wraps around the messages that will be pre-loaded
 -  ``<div id="theme-container">`` that holds our radio buttons: Night Sky, Rainbox Text, and Large Text
 - ``<div id="footer-container">`` container that holds clear all button, input field, and send button.

**Comment by zoeames** [comment]
wireframe?
