### ISSUE TITLE
messages.JSON

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#16]
# Story 
As a developer, I need user data in order for massages to appear on my page. 

# Acceptance Criteria (can have as many ands as possible)
**When**: the developer pulls down the branch
**Then**: they should have a messages.JSON file
**And**: they should have an object of users and user data that meet the technical notes below

# Technical Notes
- key1 should be "id"
- key2 should be "userId"
- key 3 should be "message"

**Comment by maryaliceorr** [comment]
```
 {
          messages = [
              {
                 "id": "message1",
                 "userId": "Anna",
                  "message": " ",
               }
           ]
       }

**Comment by zoeames** [comment]
is this really a users array or is it a messages array?
