### ISSUE TITLE
XHR call for data.json file

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#17]
# Story
As a developer, an XHR with success and fail functions should be created that also grabs our data.json file.

# Acceptance Criteria
**When** the page loads
**Then** the data in our json file should console.log

# Technical Notes
- Write ``messagesRequest`` function that starts xhr request
- export the message request into dataKeeper.js
- call the setMessages function and send the array that comes back
- will export messagesRequest function 
- data will be tested in dataKeeper file.

**Comment by zoeames** [comment]
looks good
