### ISSUE TITLE
Events.js

### ISSUE THREAD

**Issue by jessrod11** [nss-evening-cohort-7/chatty-papaphobia#18]
# Story 

As a developer, to add functionality to the html elements in index.html, there should be an events.js file with stuff in it.

# Acceptance Criteria

**When**: the ids of the buttons, message container, and input field are called 
**Then**: functions for each should be created
**And**: exported at the bottom to be used in the dom file.

# Technical Notes 

- create selectedUser function that grabs the id of each button adds class of user with border-radius and border color. Uses active boostrap class
- create clearAll function that grabs the id of the clear button and sets innerHTML of message-container to an empty string.
- there should be a console.log('e', e) which consoles our event on both the selectedUser and clearAll function to ensure we are capturing the event on click.

**Comment by zoeames** [comment]
This ticket is no longer needed.
