### ISSUE TITLE
input functions

### ISSUE THREAD

**Issue by jessrod11** [nss-evening-cohort-7/chatty-papaphobia#21]
# Story 
As a user, I want to type in a message in the input field and be able to press the Enter key or click the send button to add my message to the message container.

# Acceptance Criteria

**When**: a user types a message
**Then**: presses Enter or clicks the Send button
**Then**: The new message will print to the message container
**And** the input field clears
**And** the Send button is disabled when the input is empty

# Technical Notes 

- in events.js file
- require newMessage dom file
- create a newMessage function that grabs the user's input
- ``const inputMessage = document.getElementByID('input').innerHTML ;``
- the message needs to get pushed into the messageArray in data.js
- call the newMessageDom and pass in the messageString
- create a function called addInputEvents with two event listeners
- One event will listen for the Enter keypress and call the newMessage function
- The other will listen for a click on the send button and call the newMessage function
- Once the user enters the message, the input is cleared
- Add the disable class to the Send button when the input is empty, or the messageString length is 0
- Remove disable class when messString lenght is greater than 0
- export the addInputEvents function

**Comment by zoeames** [comment]
> const inputMessage = document.getElementByID('input').innerHTML ;

this will not work for an input - use .value

**Comment by zoeames** [comment]
shouldn't the message get saved to an array in data.js?
