### ISSUE TITLE
CSS Theme - Night Sky

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#23]
# Story 
When a user clicks on the Night Sky theme the background, text and theme of the application should change to look like a night sky. 

# Acceptance Criteria
**When**: a user arrives on a site 
**Then**: they should see the option to click on a night sky theme
**And**: when they click on the theme they should see the theme change to look like a night sky

# Technical Notes
- the id for this button should be "night-sky-button" 
- this theme should be added via class called "night-sky"

**Comment by zoeames** [comment]
how are you going to make the background the night sky?  image?
