### ISSUE TITLE
CSS Theme - Rainbow Text

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#24]
# Story 
When a user clicks on the Rainbow Text theme the background, text and theme of the application should change the text to print in a rainbow gradient. 

# Acceptance Criteria
**When**: a user arrives on a site 
**Then**: they should see the option to click on a rainbow text theme
**And**: when they click on the theme they should see the text change to a rainbow gradient

# Technical Notes
- the id for this button should be "rainbow-text-button" 
- this theme should be added via a class of "rainbow-text"
- the text being printed must be in a span for the rainbow text gradient to work
- see rainbow text CSS below

**Comment by maryaliceorr** [comment]
```
rainbow {
 background-image: -webkit-gradient( linear, left top, right top, color-stop(0, #f22), color-stop(0.15, #f2f), color-stop(0.3, #22f), color-stop(0.45, #2ff), color-stop(0.6, #2f2),color-stop(0.75, #2f2), color-stop(0.9, #ff2), color-stop(1, #f22) );
 background-image: gradient( linear, left top, right top, color-stop(0, #f22), color-stop(0.15, #f2f), color-stop(0.3, #22f), color-stop(0.45, #2ff), color-stop(0.6, #2f2),color-stop(0.75, #2f2), color-stop(0.9, #ff2), color-stop(1, #f22) );
 color:transparent;
 -webkit-background-clip: text;
 background-clip: text;
 font-size: 40px;
 -webkit-text-stroke-width: 1px;
 -webkit-text-stroke-color: #585554;
}

**Comment by zoeames** [comment]
looks good
