### ISSUE TITLE
CSS Theme - Large Text

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#25]
# Story 
When a user clicks on the Large Text theme the background, text and theme of the application should change to be in large text

# Acceptance Criteria
**When**: a user arrives on a site 
**Then**: they should see the option to click on a Large Text theme
**And**: when they click on the theme they should see the theme change to Large Text

# Technical Notes 
- the id for this button should be "large-text-button" 
- this theme should be styled by attaching a class of "large-text"

**Comment by zoeames** [comment]
looks good
