### ISSUE TITLE
new message dom

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#26]
# Story
As a user, I want to see the message I input to be printed to the message container.

# Acceptance Criteria
**When** The user sends an input message in either of two ways (keypress or click)
**Then** The message will need to be built to be used in the Dom
**And** Be printed to the Dom

# Technical Notes
- In dom js file
- in data.js create a message object and push that into the messagesArray
- Call the printToDom function

**Comment by zoeames** [comment]
We shouldn't be printing a single message.  we should be modifying an array and printing all the messages
