### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#27]
# Story
As a user, I mess up a lot and need a way to delete messages I have already sent.

# Acceptance Criteria
**When** User has input a new message
**And** Clicks on the delete button marked by an "x" next to their message
**Then** The container for that message will be hidden

# Technical Notes
- in events js file
- get elements by the class name of the delete button from newMessageBuilder function
- need a function in data.js that searches through the messagesArray finds the correct one and splices it out
- then call your printToDom again and redraw all the messages

**Comment by zoeames** [comment]
Hiding is not the same as deleting.  What is a way you can delete the message from the messageData array?
