### ISSUE TITLE
Clicking a user image

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#28]
# Story
As a user, I want to be able to toggle between different users, and be able to see which user is currently selected.

# Acceptance Criteria
**When** User clicks on the user button
**Then** The corresponding color for that user will show as a border around the image

# Technical Notes
- In events js file
- get all of the user buttons by class name
- loop through them and add a click event
- Click event calls function that adds the active class to the target
- active class adds the colorful border in main.css

**Comment by zoeames** [comment]
> And That user will be able to interact with the messages they have sent

What does this statement mean?
