### ISSUE TITLE
usernav logo and avatars

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-7/chatty-papaphobia#30]
# Story
As a user, I want to see the logo and all of the users appear at the top of the page in round icons.

# Acceptance Criteria
**When** The users load to the page 
**Then** Their image will appear in a circle

# Technical Notes
- assign a class to all user buttons
- style as a circle in main.css

**Comment by zoeames** [comment]
What happens on click of the button?  if there is another ticket for that (which there should be or this ticket is to big) this ticket should say something like when the image is clicked a console.log appears that says.....
