### ISSUE TITLE
User Nav Bar

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#7]
# Story 

As a user in order to navigate my application I must have a navbar with a logo and user icons

# Acceptance Criteria

**When**: a user arrives on the site
**Then**: they should see a navbar
**And**: it should hold the logo for the application
**And**: hold buttons that will hold user images and an id.

# Technical Notes 

- ``<div id= "user-nav">``
- use bootstrap buttons
- add an id on each button.
- ``<button id="stix"></button>``
``<button id="anna"></button>``
``<button id="ana"></button>``
``<button id="mary-alice"></button>``

**Comment by maryaliceorr** [comment]
```<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
</div>

**Comment by zoeames** [comment]
Are these buttons the image buttons?  If they are don't hard code them.  You probably don't want to use a bootstrap navbar for this project - they are very hard to customize and you want things to look a certain way.

**Comment by ghost** [comment]
Need to be consistent with how the button id's are spelled. They need to be the same as the userId from the messages.json
