### ISSUE TITLE
Bottom Footer Nav

### ISSUE THREAD

**Issue by maryaliceorr** [nss-evening-cohort-7/chatty-papaphobia#9]
# Story 
As a user in order to use the application it must have a bottom navbar with a clear messages button, a send button and a text area that's wrapped in a footer tag.

# Acceptance Criteria
**When**: a user arrives on the site
**Then**: they should see a bottom navbar
**And**: it should have a “clear all” button
**And**: it should have a "send" button
**And**: there should be a text area that says "enter message" as the default placeholder to type in a message

# Technical Notes
- "Clear all" button should have an id of “clear"
- "Enter Message" text area should have id of "input"
- "Send" button should have an id of "send"

**Comment by maryaliceorr** [comment]
```
<div class="input-group input-group-lg">
 <span class="input-group-addon" id="sizing-addon1">@</span>
 <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
</div>

**Comment by maryaliceorr** [comment]
```
<p>
  <button type="button" class="btn btn-primary btn-lg">Large button</button>
  <button type="button" class="btn btn-default btn-lg">Large button</button>
</p>

**Comment by zoeames** [comment]
Just to clarify this ticket is only for getting the display looking correct?  The event listeners will be in another ticket?
